name: pokedex
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  auto_route: ^10.1.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.2.0
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  loading_indicator: ^3.1.1
  logger: ^2.3.0
  lottie: ^3.3.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0

dev_dependencies:
  analyzer: ^7.4.5
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  hive_ce_generator: 1.9.2
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.3
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true
